### ISSUE TITLE
Sensitivity or Inertia

### ISSUE THREAD

**Issue by timlefort** [ackoDotDev/360JQueryPlugin#1]
Amazing work I love it. "Speed" refers to the autoplay animation speed. I'm looking to slow down or speed up the scroll speed sensitivity and add ease on release (intertia). 

Are either of theses supported in your script? 

Thanks a bunch in advance!

**Comment by ackoDotDev** [comment]
Hi @timlefort, glad you like it. I added dragSpeed setting that controls sensitivity. Hope this is what are you looking for.

**Comment by timlefort** [comment]
Yes. I will try this out this eve but it sounds just like what I'm looking for. I'll let you know how it works out. Thanks for the quick response as well.
